name: Scan code with Azure Text Analytics

on:
  push:
    branches:
      - main   # main 브랜치에 push될 때 실행

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run scan
        env:
          AZURE_KEY: ${{ secrets.AZURE_KEY }}
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        run: |
          python scripts/scan.py
