- name: Run PII Scan
  run: |
    echo "===== PII Scan Start ====="
    python scripts/pii_scan.py
    echo "===== PII Scan End ====="
  env:
    AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
    AZURE_KEY: ${{ secrets.AZURE_KEY }}